dmenuwebsearch: bash -> sh and ex can now handle multiple files at once

diff --git a/.local/bin/ex b/.local/bin/ex
--- a/.local/bin/ex
+++ b/.local/bin/ex
@@ -1,13 +1,16 @@
 #!/bin/sh
+# a simple utility to extract files based on extension
 
-[ -z "$1" ] && printf "You need to provide a file to extract\n" && exit
-[ ! -f "$1" ] && printf "$1 is not a valid file\n" && exit
+[ -z "$1" ] && printf "You need to provide at least one file to extract\n" && exit 1
 
-case "$1" in
+extract() {
+	case $1 in
 	*.tar.bz2|*.tbz2)
 		tar xjf "$1" ;;
 	*.tar.gz|*.tgz)
 		tar xzf "$1" ;;
+	*.tar.xz|*.txz)
+		tar xJf "$1" ;;
 	*.bz2)
 		bzip2 "$1" ;;
 	*.gz|*.Z)
@@ -17,9 +20,24 @@ case "$1" in
 	*.tar)
 		tar xf "$1" ;;
 	*.zip)
-		unzip "$1" ;;
+		unzip -q "$1" ;;
 	*.7z)
 		7z x "$1" ;;
+	*.deb)
+		ar x "$1" ;;
 	*)
-		printf "Uh oh looks like ex can't handle $1\n" ;;
-esac
+		printf "Uh oh looks like ex can't handle %s\n" "$1"
+		return 1 ;;
+	esac
+
+	printf "The content of %s has been extracted\n" "$1"
+	return 0
+}
+
+for file in $*; do
+	if [ -f "$file" ]; then
+		extract "$file"
+	else
+		printf "%s is not a valid file\n" "$file"
+	fi
+done
