merge master

diff --git a/.local/bin/ex b/.local/bin/ex
--- a/.local/bin/ex
+++ b/.local/bin/ex
@@ -1,7 +1,7 @@
 #!/bin/sh
 # a simple utility to extract files based on extension
 
-[ -z "$1" ] && printf "You need to provide file(s) to extract\n" && exit 1
+[ -z "$1" ] && printf "You need to provide file(s) to extract\n" 1>&2 && exit 1
 
 extract() {
 	case $1 in
@@ -9,16 +9,14 @@ extract() {
 		tar xjf "$1" ;;
 	*.tar.gz|*.tgz)
 		tar xzf "$1" ;;
-	*.tar.xz|*.txz)
-		tar xJf "$1" ;;
+	*.tar.xz|*.tar)
+		tar xf "$1" ;;
 	*.bz2)
 		bzip2 "$1" ;;
 	*.gz|*.Z)
 		gzip -d "$1" ;;
 	*.rar)
 		unrar x "$1" ;;
-	*.tar)
-		tar xf "$1" ;;
 	*.zip)
 		unzip -q "$1" ;;
 	*.7z)
@@ -28,7 +26,7 @@ extract() {
 	*.zst)
 		unzstd "$1" ;;
 	*)
-		printf "Uh oh looks like ex can't handle %s\n" "$1"
+		printf "Uh oh looks like ex can't handle %s\n" "$1" 1>&2
 		return 1 ;;
 	esac
 
diff --git a/.local/bin/quand b/.local/bin/quand
--- a/.local/bin/quand
+++ b/.local/bin/quand
@@ -1,16 +1,16 @@
 #!/bin/sh
 
-VERSION="1.0.0"
-CONF="$XDG_CONFIG_HOME/quand/config"
+VERSION="1.0.1"
+CONF="${XDG_CONFIG_HOME:-$HOME/.config}/quand/config"
 
 language="${LANG:-en_US.utf-8}"
-calendar="$XDG_CONFIG_HOME/quand/calendar"
+calendar="${XDG_CONFIG_HOME:-$HOME/.config}/quand/calendar"
 editor="${EDITOR:-vi}"
 header=0
 past=0
 future=1
 yesterday="yesterday"
-today="today"
+today="\033[1mtoday"
 tomorrow="tomorrow"
 mondayfirst=1
 
@@ -22,7 +22,7 @@ trimspaces() {
 	set -f
 	old_ifs=$IFS
 	IFS=" "
-	# shellcheck disable=2086
+	# shellcheck disable=SC2086
 	set -- $1
 	IFS=
 	printf '%s\n' "$*"
@@ -42,40 +42,48 @@ print() {
 	while IFS= read -r line || [ -n "$line" ]; do
 		case $line in
 		"$year $1"*|"* $1"*)
-			printf '%s\n' "$2    $line" ;;
+			printf "$2\033[m    %s\n"  "$line" ;;
 		esac
 	done < "$calendar"
 }
 
 
-printhelp() {
-	printf "read the README\n"
+usage() {
+	printf 'Usage: %s [options]
+
+Options:
+no option             | default
+                      |
+e|edit                | edit the calendar file
+c|cal                 | print the calendar
+                      │
+-h|--help             │ Print this help message and exit
+-v|--version          | Print the version\n' "${0##*/}" 1>&2
 }
 
 getsettings() {
-# shellcheck disable=2046
 	while IFS= read -r line || [ -n "$line" ]; do
 		case $line in
 		"language"*)
-			language="$(lstrip $(trimspaces "$line") "language=")" ;;
+			language="$(lstrip "$(trimspaces "$line")" "language=")" ;;
 		"calendar"*)
-			calendar="$(lstrip $(trimpspaces "$line") "calendar=")" ;;
+			calendar="$(lstrip "$(trimspaces "$line")" "calendar=")" ;;
 		"editor"*)
-			editor="$(lstrip $(trimspaces "$line") "editor=")" ;;
+			editor="$(lstrip "$(trimspaces "$line")" "editor=")" ;;
 		"header"*)
-			header="$(lstrip $(trimspaces "$line") "header=")" ;;
+			header="$(lstrip "$(trimspaces "$line")" "header=")" ;;
 		"future"*)
-			future="$(lstrip $(trimspaces "$line") "future=")" ;;
+			future="$(lstrip "$(trimspaces "$line")" "future=")" ;;
 		"past"*)
-			past="$(lstrip $(trimspaces "$line") "past=")" ;;
+			past="$(lstrip "$(trimspaces "$line")" "past=")" ;;
 		"yesterday"*)
-			yesterday="$(lstrip $(trimspaces "$line") "yesterday=")" ;;
+			yesterday="$(lstrip "$(trimspaces "$line")" "yesterday=")" ;;
 		"today"*)
-			today="$(lstrip $(trimspaces "$line") "today=")" ;;
+			today="$(lstrip "$(trimspaces "$line")" "today=")" ;;
 		"tomorrow"*)
-			tomorrow="$(lstrip $(trimspaces "$line") "tomorrow=")" ;;
+			tomorrow="$(lstrip "$(trimspaces "$line")" "tomorrow=")" ;;
 		"mondayfirst"*)
-			mondayfirst="$(lstrip $(trimspaces "$line") "mondayfirst=")" ;;
+			mondayfirst="$(lstrip "$(trimspaces "$line")" "mondayfirst=")" ;;
 		esac
 	done < "$CONF"
 }
@@ -93,29 +101,32 @@ main() {
 
 	case $* in
 	-v|--version)
-		printf '%s\n' "${0##*/} $VERSION"
+		printf '%s %s\n' "${0##*/}" "$VERSION" 1>&2
 	 	return 0 ;;
 	-h|--help)
-		printhelp
+		usage
 		return 0 ;;
-	e|edit|-e|--edit)
+	e|edit)
 		"$editor" "$calendar"
 		return 0 ;;
-	c|calendar|-c|--calendar)
+	c|cal)
 		calendar
 		return 0 ;;
 	'')
 		exec 2>/dev/null ;;
+	*)
+		printf 'Error: unknown option %s\n' "$*" 1>&2
+		usage
+		return 1 ;;
 	esac
 
-	if [ ! -f "$calendar" ]; then
-		printf '%s\n' "$calendar is not a valid file"
+	[ ! -f "$calendar" ] &&
+		printf 'Error: %s is not a valid file\n' "$calendar" 1>&2 &&
 		return 1
-	fi
 
-	year="$(date "+%Y")"
+	year="$(date "+%Y")" # this is inaccurate
 
-	[ "$header" = 1 ] && printf '%s\n\n' "$(date)"
+	[ "$header" = 1 ] && printf '%s\n\n' "$(LC_ALL="$language" date)"
 
 	while [ "$past" -gt 1 ]; do
 		print "$(getday "-$past")" "$(getnameday "-$past")"
