add mpv music scripts, optimize musiccmd

diff --git a/.local/bin/musiccmd b/.local/bin/musiccmd
--- a/.local/bin/musiccmd
+++ b/.local/bin/musiccmd
@@ -1,23 +1,26 @@
 #!/bin/sh
 # helper for the music script
-# to force pause do: printf "{ \"command\": [\"set_property\", \"pause\", true] }\n" | socat - /tmp/mpvsocket 1> /dev/null
+# to force pause do: printf '{ "command": ["set_property", "pause", true] }\n' | socat - /tmp/mpvsocket 1> /dev/null
 
-CMD="${1:-$(printf "🆙update\n⏯️pause/play\n⏭️next\n⏮️prev\n⭐favorite\n📢volume\n🔳stop\n⬇️download\n🖼️thumbnail" | dmenu -i -p "musiccmd")}"
+[ $(pgrep music) ] 2> /dev/null && notify-send "There is no music playing" && exit 1
 
-trimquotes() {
-	set -f
-	old_ifs=$IFS
-	IFS=\"
-	set -- $1
-	IFS=
-	printf '%s\n' "$*"
-	IFS=$old_ifs
-	set +f
+CMD="${1:-$(printf '⏯️pause/play\n⏭️next\n⏮️prev\n📢volume\n🔳stop\n⭐favorite\n⬇️download\n🖼️thumbnail' | dmenu -i -p "musiccmd")}"
+
+strip() {
+	tmp="${1##{\"data\":\"}"
+	printf '%s\n' "${tmp%%\",\"request_id\":0,\"error\":\"success\"\}}"
 }
 
+stripvol() {
+	tmp="${1##{\"data\":}"
+	printf '%s\n' "${tmp%%.000000,\"request_id\":0,\"error\":\"success\"\}}"
+}
+
+
 getthumbnail() {
-	path="$(trimquotes "$(printf "{ \"command\": [\"get_property\", \"path\"] }\n"\
-		| socat - /tmp/mpvsocket 2> /dev/null | jq ".data")")"
+	path="$(strip "$(printf '{ "command": ["get_property", "path"] }\n'\
+		| socat - /tmp/mpvsocket 2> /dev/null)")"
+
 	case $path in
 	*youtube.com*)
 		yt-dlp --skip-download --force-overwrites --write-thumbnail\
@@ -30,12 +33,13 @@ getthumbnail() {
 
 download() {
 	yt-dlp -f "ba" -x --embed-thumbnail --audio-format mp3 --postprocessor-args "-ar 44100"\
-		-o"%(title)s [%(id)s].%(ext)s" -P "$1" "$2"
+		-o"%(title)s [%(id)s].%(ext)s" -P "$1" "$2" || notify-send "I can't download, this is a local file"
 }
 
 addtofav() {
-	path="$(trimquotes "$(printf "{ \"command\": [\"get_property\", \"path\"] }\n"\
-		| socat - /tmp/mpvsocket 2> /dev/null | jq ".data")")"
+	path="$(strip "$(printf '{ "command": ["get_property", "path"] }\n'\
+		| socat - /tmp/mpvsocket 2> /dev/null)")"
+
 	case $path in
 	*youtube.com*)
 		download "$XDG_MUSIC_DIR/favorite" "$path" ;;
@@ -46,26 +50,29 @@ addtofav() {
 
 case "$CMD" in
 cycle|*pause|*play)
-	printf "cycle pause\n" | socat - /tmp/mpvsocket ;;
+	printf 'cycle pause\n' | socat - /tmp/mpvsocket
+	kill -43 "$(pidof dwmblocks)" ;;
 *next)
-	printf "playlist-next\n" | socat - /tmp/mpvsocket ; sleep 0.1 ;;
+	printf 'playlist-next\n' | socat - /tmp/mpvsocket ;;
 *prev)
-	printf "playlist-prev\n" | socat - /tmp/mpvsocket ; sleep 0.1 ;;
+	printf 'playlist-prev\n' | socat - /tmp/mpvsocket ;;
 *favorite)
 	addtofav ;;
 *volume)
-	printf "{ \"command\": [\"set_property\", \"volume\",\
-		${2:-$(printf "" | dmenu -p "Current volume:$(printf "{ \"command\": [\"get_property\", \"volume\"] }\n"\
-		| socat - /tmp/mpvsocket | jq ".data")")}] }\n"\
-		| socat - /tmp/mpvsocket ;; # 1> /dev/null
+	[ -z "$2" ] &&
+		CURRENT="$(stripvol "$(printf '{ "command": ["get_property", "volume"] }\n'\
+			| socat - /tmp/mpvsocket)")"
+
+	printf '{ "command": ["set_property", "volume", %s] }\n'\
+		"${2:-$(printf "" | dmenu -p "Current volume:$CURRENT")}"\
+		| socat - /tmp/mpvsocket 1> /dev/null ;;
 *stop)
-	printf "stop\n" | socat - /tmp/mpvsocket ;;
+	printf 'stop\n' | socat - /tmp/mpvsocket
+	kill -43 "$(pidof dwmblocks)" ;;
 *download)
-	download "$XDG_MUSIC_DIR/download"
-		"$(trimquotes "$(printf "{ \"command\": [\"get_property\", \"path\"] }\n"\
-		| socat - /tmp/mpvsocket 2> /dev/null | jq ".data")")" ;;
+	download "$XDG_MUSIC_DIR/download"\
+		"$(strip "$(printf '{ "command": ["get_property", "path"] }\n'\
+		| socat - /tmp/mpvsocket 2> /dev/null)")" ;;
 *thumbnail)
 	getthumbnail && sxiv "$XDG_CACHE_HOME/thumbnail.jpg" ;;
 esac
-
-kill -43 $(pidof dwmblocks)
