update

diff --git a/.local/bin/musiccmd b/.local/bin/musiccmd
--- a/.local/bin/musiccmd
+++ b/.local/bin/musiccmd
@@ -1,34 +1,54 @@
 #!/bin/sh
 # helper for the music script
-# to force pause do:
-#printf '{ "command": ["set_property", "pause", true] }\n'\
-#	| socat - /tmp/mpvsocket 1> /dev/null
+# dependencies: music, mpv, socat, yt-dlp, ffmpeg, imagemagick
+# optional dependencies: dwmblocks, libnotify, herbe
 
-if ! pgrep -x music >/dev/null; then
-	kill -35 "$(pidof dwmblocks)"
-	herbe "Error: There is no music playing" "Do you want to play some ?" &&
-		music
- 	exit 1
-fi
-
-CMD="${1:-$(printf '⏯️pause/play\n⏭️next\n⏮️prev\n📢volume\n🔳stop\n⭐favorite\n⬇️download\n🖼️thumbnail' | dmenu -i -p "musiccmd")}"
 FAVDIR="${XDG_MUSIC_DIR:-$HOME/Music}/favorite"
 DLDIR="${XDG_MUSIC_DIR:-$HOME/Music}/download"
 CACHE="${XDG_CACHE_HOME:-$HOME/.cache}"
+IMG="nsxiv"
 
-strip() {
-	tmp="${1##{\"data\":\"}"
-	printf '%s\n' "${tmp%%\",\"request_id\":0,\"error\":\"success\"\}}"
+getpath() {
+	tmp="$(printf '{ "command": ["get_property", "path"] }\n'\
+		| socat - /tmp/mpvsocket)"
+	tmp="${tmp#{\"data\":\"}"
+	path="${tmp%\",\"request_id\":0,\"error\":\"success\"\}}"
 }
 
-stripvol() {
-	tmp="${1##{\"data\":}"
-	printf '%s\n' "${tmp%%.000000,\"request_id\":0,\"error\":\"success\"\}}"
+getvol() {
+	tmp="$(printf '{ "command": ["get_property", "volume"] }\n'\
+		| socat - /tmp/mpvsocket)"
+	tmp="${tmp#{\"data\":}"
+	printf '%s\n' "${tmp%.000000,\"request_id\":0,\"error\":\"success\"\}}"
 }
 
-setpath() {
-	path="$(strip "$(printf '{ "command": ["get_property", "path"] }\n'\
-		| socat - /tmp/mpvsocket 2> /dev/null)")"
+download() {
+	mkdir -p "$1"
+	notify-send "Downloading '$path' to '$1'"
+	if yt-dlp -f "ba" -x --embed-thumbnail --audio-format mp3\
+			-o"%(title)s [%(id)s].%(ext)s" -P "$1" "$path"; then
+		notify-send "'$path' successfuly downloaded to '$2'"
+		return 0
+	else
+		notify-send "Error: '$path' couldn't be downloaded"
+		return 1
+	fi
+}
+
+addtofav() {
+	case $path in
+	*youtube.com*)
+		download "$FAVDIR" ;;
+	*)
+		mkdir -p "$FAVDIR"
+		if cp "$path" "$FAVDIR"; then
+			notify-send "'$path' was copied to '$FAVDIR'"
+			return 0
+		else
+			notify-send "'$path' couldn't be copied to '$FAVDIR'"
+			return 1
+		fi ;;
+	esac
 }
 
 getthumbnail() {
@@ -43,54 +63,54 @@ getthumbnail() {
 	esac
 }
 
-download() {
-	mkdir -p "$1"
-	notify-send "Downloading '$2'"
-	yt-dlp -f "ba" -x --embed-thumbnail --audio-format mp3\
-		-o"%(title)s [%(id)s].%(ext)s" -P "$1" "$2" ||
-		notify-send "Error: can't download, this is a local file"
-}
 
-addtofav() {
-	case $path in
-	*youtube.com*)
-		download "$FAVDIR" "$path" ;;
-	*)
-		mkdir -p "$FAVDIR"
-		cp "$path" "$FAVDIR" ;;
+main() {
+	if ! pgrep -x music >/dev/null; then
+		kill -35 "$(pidof dwmblocks)"
+		herbe "Error: There is no music playing"\
+			"Do you want to play some ?" &&
+			music
+		return 1
+	fi
+
+	cmd="${1:-$(printf '⏯️pause/play\n⏭️next\n⏮️prev\n📢volume\n🔳stop
+⭐favorite\n⬇️download\n🖼️thumbnail' | dmenu -i -p "musiccmd")}"
+
+	case "$cmd" in
+	cycle|*pause|*play)
+		printf 'cycle pause\n' | socat - /tmp/mpvsocket
+		kill -35 "$(pidof dwmblocks)" ;;
+	*next)
+		printf 'playlist-next\n' | socat - /tmp/mpvsocket ;;
+	*prev)
+		printf 'playlist-prev\n' | socat - /tmp/mpvsocket ;;
+	*volume)
+		printf '{ "command": ["set_property", "volume", %s] }\n'\
+			"${2:-$(true | dmenu -p "Current volume: $(getvol)")}"\
+			| socat - /tmp/mpvsocket 1> /dev/null ;;
+	*stop)
+		printf 'stop\n' | socat - /tmp/mpvsocket
+		kill -35 "$(pidof dwmblocks)" ;;
+	*favorite|fav)
+		getpath
+		addtofav ;;
+	*download)
+		getpath
+		download "$DLDIR" ;;
+	*thumbnail)
+		getpath
+		if getthumbnail; then
+			$IMG "$CACHE/thumbnail.jpg"
+		else
+			notify-send "Error: can't get thumbnail"
+			return 1
+		fi ;;
+	path)
+		getpath
+		printf '%s\n' "$path" ;;
+	vol)
+		getvol ;;
 	esac
 }
 
-case "$CMD" in
-cycle|*pause|*play)
-	printf 'cycle pause\n' | socat - /tmp/mpvsocket
-	kill -35 "$(pidof dwmblocks)" ;;
-*next)
-	printf 'playlist-next\n' | socat - /tmp/mpvsocket ;;
-*prev)
-	printf 'playlist-prev\n' | socat - /tmp/mpvsocket ;;
-*favorite|fav)
-	setpath
-	addtofav ;;
-*volume)
-	[ -z "$2" ] &&
-		current="$(stripvol "$(printf '{ "command": ["get_property", "volume"] }\n'\
-			| socat - /tmp/mpvsocket)")"
-
-	printf '{ "command": ["set_property", "volume", %s] }\n'\
-		"${2:-$(printf "" | dmenu -p "Current volume:$current")}"\
-		| socat - /tmp/mpvsocket 1> /dev/null ;;
-*stop)
-	printf 'stop\n' | socat - /tmp/mpvsocket
-	kill -35 "$(pidof dwmblocks)" ;;
-*download)
-	setpath
-	download "$DLDIR" "$path" &&
-		notify-send "$path successfuly downloaded at '$DLDIR'" ;;
-*thumbnail)
-	setpath
-	getthumbnail && nsxiv "$CACHE/thumbnail.jpg" ;;
-path)
-	setpath
-	printf '%s\n' "$path" ;;
-esac
+main "$@"
