Add more softwares and big changes to plumber
- Add zellij as terminal multiplexer and session manager:
  - tmux: I don't like its defaults and I cba configuring it
  - abduco: I really like it but incomplete redraws are too annoying to
    use it alone so I tried with
    - mtm: no configuration is fine but the default controls are not
      vim-like
    - dvtm: is pretty good with sane default but the colors never work
  - zellij: even though it's a gigantic binary the first time user
    experience is just too good to not use it and it keeps getting
    better
- Add paru thus removing aurinstall and aursearch, this also means that
  the Makefile is now completely deprecated.
- Add syncthing.
- Add senpai as IRC client.
- Add zoxide to replace cd.
- Add comfy-line-numbers plugin to nvim which is kinda buggy for large
  files.
- Move pkgbuilds to https://github.com/ratakor/rcp thanks to paru.
- Move notes from $XDG_DATA_HOME/notes to $XDG_DOCUMENTS_DIR/notes.
- Remove useless .desktop files in $XDG_DATA_HOME/applications and update
  mimeapps.list accordingly.
- Rework plumber a lot:
  - Add zellij support.
  - Clean up code (setsid -> open/openterm).
  - Remove --sel command, just use `plumber "$(wl-paste)"`.
  - Replace dmenuhandler with plumber --dmenu.
- Update newsboat config for wayland (never too late lol).

diff --git a/.local/bin/plumber b/.local/bin/plumber
--- a/.local/bin/plumber
+++ b/.local/bin/plumber
@@ -1,23 +1,51 @@
-#!/bin/sh
-# Copywrong © 2023 Ratakor. Under ISC License.
+#!/bin/sh --
 # plumber 🪠
-# dependencies:
-#   - default programs
-#   - xdo
-#   - wl-clipboard
+# Copyright © 2025 Ratakor. Under ISC License.
 # shellcheck disable=SC2086
 
-# default programs
-WEB="xdg-open"
-TEXT="$TERMINAL -e $EDITOR"
-VIDEO="mpv --ytdl-format=22 --loop"
-AUDIO="music --shuffle"
-PIC="imv"
-DOC="zathura"
-DIR="$TERMINAL -e yazi"
+# default programs:
+# use open for gui and openterm for terminal applications
+# currently assuming that WEB, VIDEO and AUDIO handle URLs
+WEB="open ${BROWSER:-"xdg-open"}"
+TEXT="openterm $EDITOR"
+VIDEO="open mpv --ytdl-format=22 --loop"
+AUDIO="open music"
+PIC="open imv"
+DOC="open zathura"
+DIR="openterm yazi"
+DMENU=${DMENU:-"dmenu -i"}
 
+TMPDIR=${XDG_RUNTIME_DIR:-/tmp}/plumber
 HISTDIR=${XDG_STATE_HOME:-$HOME/.local/state}/plumber
 HISTFILE=$HISTDIR/history
+
+open() {
+	setsid -f "$@" >/dev/null 2>&1
+}
+
+openterm() {
+	if [ -n "$ZELLIJ" ]; then
+		zellij action new-pane -- "$@"
+	else
+		open $TERMINAL -e "$@"
+	fi
+}
+
+# mfw 0 is true and 1 is false
+isurl() {
+	case "$1" in
+	http://*|https://*|git://*|irc://*|ircs://*|file://*)
+		return 0 ;;
+	*)
+		return 1 ;;
+	esac
+}
+
+# The downloaded file "$1" will be saved to "$TMPDIR/$file"
+tmpdl() {
+	file=$(printf '%s' "$1" | sed "s/.*\///;s/%20/ /g")
+	curl -sL "$1" > "$TMPDIR/$file"
+}
 
 openurls() {
 	case "$1" in
@@ -25,32 +53,23 @@ openurls() {
 		openfile "${1##file://}" ;;
 	*.mkv|*.webm|*.mp4|*.mov|*youtube.com/watch*|*youtube.com/playlist*|\
 		*youtube.com/shorts*|*youtu.be*|*inv*/playlist*|*inv*/watch*)
-		setsid -f $VIDEO "$1" >/dev/null 2>&1 ;;
+		$VIDEO "$1" ;;
 	*.mp3|*.flac|*.opus|*mp3?source*|*.ogg|*.wav|*soundcloud.com*)
-		setsid -f $AUDIO "$1" >/dev/null 2>&1 ;;
+		$AUDIO "$1" ;;
 	*.png|*.jpg|*.jpeg|*.gif|*.webp|*.bmp)
-		file=$(printf '%s' "$1" | sed "s/.*\///;s/%20/ /g")
-		curl -sL "$1" > "/tmp/$file" &&
-			$PIC "/tmp/$file" >/dev/null 2>&1 & ;;
+		tmpdl "$1" && $PIC "$TMPDIR/$file" ;;
 	*.pdf|*.ps|*.cbz|*.cbr|*.djvu|*.epub)
-		file=$(printf '%s' "$1" | sed "s/.*\///;s/%20/ /g")
-		curl -sL "$1" > "/tmp/$file" &&
-			$DOC "/tmp/$file" >/dev/null 2>&1 & ;;
-	*wp.com/stonetoss.com*)
-		file=$(printf '%s' "${1%"?resize=150%2C150&ssl=1"}" |\
-			sed "s/.*\///;s/%20/ /g")
-		curl -sL "${1%"?resize=150%2C150&ssl=1"}" > "/tmp/$file" &&
-			$PIC "/tmp/$file" >/dev/null 2>&1 & ;;
+		tmpdl "$1" && $DOC "$TMPDIR/$file" ;;
 	git://*|git@*|*.git)
-		"$TERMINAL" -e git clone "$1" ;;
+		openterm git clone "$1" ;;
 	*)
-		setsid -f $WEB "$1" >/dev/null 2>&1 ;;
+		$WEB "$1" ;;
 	esac
 }
 
 openfile() {
 	if [ -d "$1" ]; then
-		setsid -f $DIR "$1" >/dev/null 2>&1
+		$DIR "$1"
 		return
 	fi
 
@@ -61,60 +80,64 @@ openfile() {
 
 	case "$1" in
 	*.mkv|*.webm|*.mp4|*.mov)
-		setsid -f $VIDEO "$1" >/dev/null 2>&1 ;;
+		$VIDEO "$1" ;;
 	*.mp3|*.flac|*.opus|*.ogg|*.wav)
-		setsid -f $AUDIO "$1" >/dev/null 2>&1 ;;
+		$AUDIO "$1" ;;
 	*.png|*.jpg|*.jpeg|*.gif|*.webp|*.bmp)
-		setsid -f $PIC "$1" >/dev/null 2>&1 ;;
+		$PIC "$1" ;;
 	*.pdf|*.ps|*.cbz|*.cbr|*.djvu|*.epub)
-		setsid -f $DOC "$1" >/dev/null 2>&1 ;;
+		$DOC "$1" ;;
 	*)
-		setsid -f $TEXT "$1" >/dev/null 2>&1 ;;
+		$TEXT "$1" ;;
 	esac
 }
 
-checksel() {
-	case "$1" in
-	http://*|https://*|irc://*|ircs://*|git://*|git@*)
-		openurls "$1" ;;
-	/*)
-		opensel "$1" "$1" ;;
-
-	*)
-		pid=$(pstree -lpA "$(xdo pid)" | tail -n 1 |\
-			awk -F '---' '{print $NF}' | sed -re 's/[^0-9]//g')
-		opensel "$(readlink "/proc/$pid/cwd")/$1" "$1" ;;
-	esac
-}
-
-opensel() {
-	if [ -d "$1" ]; then
-		case $1 in
-		"${XDG_MUSIC_DIR:-$HOME/Music}"/*)
-			setsid -f $AUDIO "$1" >/dev/null 2>&1 ;;
-		*)
-			xdo kill
-			$TERMINAL -e sh -c "cd $1; $SHELL" ;;
-		esac
-		return
-	fi
-
-	[ ! -f "$1" ] && return
-
-	case "$1" in
-	*.mkv|*.webm|*.mp4|*.mov)
-		setsid -f $VIDEO "$1" >/dev/null 2>&1 ;;
-	*.mp3|*.flac|*.opus|*.ogg|*.wav)
-		setsid -f $AUDIO "$1" >/dev/null 2>&1 ;;
-	*.png|*.jpg|*.jpeg|*.gif|*.webp|*.bmp)
-		setsid -f $PIC "$1" >/dev/null 2>&1 ;;
-	*.pdf|*.ps|*.cbz|*.cbr|*.djvu|*.epub)
-		setsid -f $DOC "$1" >/dev/null 2>&1 ;;
-	*)
-		pid=$(xdo pid)
-		xdo hide -p "$pid"
-		$TEXT "$1" >/dev/null 2>&1
-		xdo show -p "$pid" ;;
+# TODO: ytdl + randwp
+opendmenu() {
+	case "$(printf '%s\nbrowser\naudio\nvideo\nimage\ndocument\neditor
+yt-dlp\nmusic-dlp\nsetbg' "$1" | $DMENU -p "Open with")" in
+	"$1")
+		wl-copy "$1" 2>/dev/null ||\
+			printf '%s' "$1" | xclip 2>/dev/null ||\
+			printf '%s' "$1" | xsel 2>/dev/null ;;
+	browser)
+		$WEB "$1" ;;
+	audio)
+		$AUDIO "$1" ;;
+	video)
+		$VIDEO "$1" ;;
+	image)
+		if isurl "$1"; then
+			tmpdl "$1" && $PIC "$TMPDIR/$file"
+		else
+			$PIC "$1"
+		fi ;;
+	document)
+		if isurl "$1"; then
+			tmpdl "$1" && $DOC "$TMPDIR/$file"
+		else
+			$DOC "$1"
+		fi ;;
+	editor)
+		if isurl "$1"; then
+			tmpdl "$1" && $TEXT "$TMPDIR/$file"
+		else
+			$TEXT "$1"
+		fi ;;
+	yt-dlp)
+		open ytdl v "$1" ;;
+	music-dlp)
+		if [ "$(printf 'no\nyes' | $DMENU -p 'Playlist?')" = "yes" ]; then
+			open ytdl p "$1"
+		else
+			open ytdl m "$1"
+		fi ;;
+	setbg)
+		if isurl "$1"; then
+			tmpdl "$1" && open randwp "$TMPDIR/$file"
+		else
+			open randwp "$1"
+		fi ;;
 	esac
 }
 
@@ -125,9 +148,9 @@ Usage: ${0##*/} [options] [args]
 
 Options:
   no option [args]    | Try to guess what to do
-  -u|--url [urls]     | Open the urls
-  -f|--file [files]   | Open the files or the folders
-  -s|--sel            | Use the selection buffer instead, Plan9's way
+  -u|--url [urls]     | Open URLs
+  -f|--file [files]   | Open files or directories
+  -d|--dmenu [arg]    | Use dmenu to select how to handle the argument
   -h|--help           │ Print this help message
 
 Config:
@@ -138,11 +161,17 @@ Config:
   picture      = $PIC
   document     = $DOC
   file manager = $DIR
+  dmenu        = $DMENU
+
+  tmpdir       = $TMPDIR
+  history      = $HISTFILE
 EOF
 }
 
 main() {
 	mkdir -p "$HISTDIR"
+	mkdir -p "$TMPDIR"
+
 	case "$1" in
 	-u|--url)
 		shift
@@ -166,33 +195,28 @@ main() {
 			printf '%s\n' "$arg" >> "$HISTFILE"
 			openfile "$arg"
 		done ;;
-	-s|--sel|'')
-		sel=$(wl-paste)
-		sel=${sel#"${sel%%[![:space:]]*}"}
-		wl-copy --clear
-
-		if [ -z "$sel" ]; then
-			printf '\033[31mError:\033[m selection buffer is empty\n' >&2
-			usage
-			return 1
-		fi
-		printf '%s\n' "$sel" >> "$HISTFILE"
-		checksel "$sel" ;;
-	-h|--help)
+	-d|--dmenu)
+		shift
+		arg=${1:-$(true | $DMENU -p 'Paste URL or file path')}
+		[ -z "$arg" ] && return
+		printf '%s\n' "$arg" >> "$HISTFILE"
+		opendmenu "$arg" ;;
+	-h|--help|'')
 		usage ;;
 	-*)
-		printf '\033[31mError:\033[m unknown option\n' >&2
+		printf "\033[31mError:\033[m unknown option '%s'\n" "$1" >&2
 		usage
 		return 1 ;;
 	*)
 		for arg in "$@"; do
-			case "$arg" in
-			http://*|https://*|git://*|irc://*|ircs://*|file://*)
-				openurls "$arg" ;;
-			*)
-				openfile "$arg" ;;
-			esac
-		done
+			printf '%s\n' "$arg" >> "$HISTFILE"
+			if isurl "$arg"; then
+				openurls "$arg"
+			else
+				openfile "$arg"
+			fi
+
+		done ;;
 	esac
 }
 
